[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.0"
NODE_VERSION = "22"
TZ = "Europe/Berlin"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"